server:
  port: 9999

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: Quant2019
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CoinExchange?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
