server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service-router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: test_router
          uri: https://www.aliyun.com
          predicates:
            - Path=/product
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      filter:
        enabled: true
      datasource:
        ds1:
          #          file:
          #            file: classpath:gw-flow.json
          #            ruleType: gw-flow
          nacos:
            data-id: gw-flow
            server-addr: 127.0.0.1:8848
            rule-type: gw_flow
        ds2:
          #          file:
          #            file: classpath:api-group.json
          #            ruleType: gw_api_group
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: gw_api_group
            rule-type: gw_api_group
  redis:
    host: 127.0.0.1
    port: 6379
    password: Quant2019

