server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service-router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: test_router
          uri: https://www.aliyun.com
          predicates:
            - Path=/product
    sentinel:
      filter:
        enabled: true
      datasource:
        ds1.file:
          file: classpath:router-flow.json
          ruleType: gw-flow
        ds2.file:
          file: classpath:api-flow.json
          ruleType: gw_api_group
